#!/bin/bash

## vars
PROJECT=github.com/itang/yunshang/main
tasks=$*

## functions
function do_godoc() {
  pid=`pgrep godoc`
  if [ "$pid" != "" ]; then
    echo "kill $pid && godoc -http=:8080 &"
    kill $pid
    echo "> godoc at http://localhost:8080"
    godoc -http=:8080 &
  fi
}

function do_dev_task() {
  echo "go fmt ${PROJECT}/..." && go fmt ${PROJECT}/...
  do_godoc;
  revel run ${PROJECT} dev
}

## main
(
cd main;
for task in $tasks; do
case $task in
    ""|run|dev) do_dev_task;;
          prod) revel run ${PROJECT} prod;;
          test) revel test ${PROJECT} dev;;
       package) revel package ${PROJECT} ;;
           fmt) go fmt ${PROJECT}/...;;
        initdb) go run ../tools/initdb.go;;
          psql) psql -U dbuser -d yunshangdb -h 127.0.0.1 -p 5432;;
             *) revel $task ${PROJECT} ;;
esac
done
)
